
spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

oauth:
  authorization:
    auth-token: "http://127.0.0.1:9090/oauth/authorize"
    client-id: "front-end"
    client-secret: "front"
    response-type: "code"
    access-token: "http://localhost:9090/oauth/token"
    grant-type: "authorization_code"
    resource-url: "http://127.0.0.1:9098/admin"

